# makefile for wmbt_linux64
#
# To make, cd into wiced_btsdk/tools/btsdk-utils/wmbt/bin and execute the below:
#
# $ make -f Linux64/Makefile
#
include ../common/Makefile

TARGET:= wmbt
all :  $(TARGET)
